# 头部菜单，title: link
menu:
  Whoami: /whoami
  Github: https://github.com/wangd1

# 是否显示目录
TOC: false

# 是否自动播放音乐
autoplay: false

# 默认音乐
mp3: 
  - http://link.hhtjim.com/kg/86E8BF58A5A367AAD23E84BEF976BBA3.mp3
  - http://link.hhtjim.com/kg/E8E09FDEA01E1093A29131C6B1C224BB.mp3
  - http://link.hhtjim.com/kg/3C5605A1800F96C6AA1EFECE8B958371.mp3
  - http://link.hhtjim.com/kg/29C242223631B27B143CEDDF74FBFB18.mp3

# 首页封面图, 为空时取文章的cover作为封面
welcome_cover: # /img/welcome-cover.jpg

# 默认文章封面图
cover: /img/cover.jpg

# 是否关闭默认滚动条
scrollbar: true

# Gitalk 评论插件（https://github.com/gitalk/gitalk）
gitalk:
    enable: true
    # 是否自动展开评论框
    autoExpand: true
    # 应用编号
    client_id: 9feaf9c4cc7d9fa23951
    # 应用秘钥
    client_secret: 4eb08664fe9b552607228fed1737f0c59d9fe87d
    # issue仓库名
    repo: gittalk-commet
    # Github名
    admin: wangd1
    owner: wangd1

# 网站关键字
keywords: 如初

# 要使用google_analytics进行统计的话，这里需要配置ID
google_analytics: UA-131114986-1

# 网站ico
favicon: /img/favicon.png

# rss文件
rss: atom.xml
